CREATE TABLE Fragrance (
  name VARCHAR(80) PRIMARY KEY,
  rating INT,
  CREATOR NOT NULL;
);

CREATE TABLE Scentfamily (
  PRIMARY KEY
);

CREATE TABLE Users (
  username VARCHAR(45) PRIMARY KEY;
);
